server:
  port: 8001

spring:
  application:
    name: cloud-payment
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      naming:
        physical-strategy: utils.UpperCasePhysicalNamingStrategy
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        show_sql: true
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=cloud01;applicationName=${spring.application.name};selectMethod=cursor;sendStringParametersAsUnicode=true
    username: sl
    password: wayne
